version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run: sudo gem install review
      - run: sudo npm install -g textlint
      - run: sudo npm install -g textlint-rule-max-ten textlint-rule-spellcheck-tech-word textlint-rule-no-mix-dearu-desumasu
      - run: sudo pip install awscli
      - run: make pdf
